In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import linear_model
import statsmodels.api as sm
import tkinter as tk

In [2]:
df5 = pd.read_csv("fifth.csv", sep = ',', header=[0], encoding="utf-8") 
print(df5)

      Unnamed: 0  year  state  level  total_people_by_state_and_level  \
0              0     5      1      2                             3157
1              1     5      1      1                           118401
2              2     5      1      3                             5092
3              3     5      1      7                           257632
4              4     5      1      4                           140654
5              5     5      1      5                           339865
6              6     5      1      6                            57276
7              7     5      1      9                            14992
8              8     5      1      8                            64577
9              9     5      2      2                             3007
10            10     5      2      1                           294185
11            11     5      2      3                            20085
12            12     5      2      7                           748055
13            13     5      2      4                           423938
14            14     5      2      5                          1065217
15            15     5      2      6                           107923
16            16     5      2      9                            30403
17            17     5      2      8                           171619
18            18     5      3      2                             4601
19            19     5      3      1                           107013
20            20     5      3      3                            10934
21            21     5      3      7                           163214
22            22     5      3      4                           101715
23            23     5      3      5                            53931
24            24     5      3      6                            24307
25            25     5      3      9                             6810
26            26     5      3      8                            38176
27            27     5      4      2                            27881
28            28     5      4      1                           270087
29            29     5      4      3                             5336
...          ...   ...    ...    ...                              ...
4128        4128    18     29      6                            44671
4129        4129    18     29      9                             7646
4130        4130    18     29      8                            59344
4131        4131    18     30      2                            54009
4132        4132    18     30      1                          3160801
4133        4133    18     30      3                            84839
4134        4134    18     30      7                          2015651
4135        4135    18     30      4                          1224417
4136        4136    18     30      5                          1046229
4137        4137    18     30      6                           310866
4138        4138    18     30      9                            68678
4139        4139    18     30      8                           684743
4140        4140    18     31      2                             9065
4141        4141    18     31      1                           421520
4142        4142    18     31      3                            18337
4143        4143    18     31      7                           622548
4144        4144    18     31      4                           366700
4145        4145    18     31      5                           730106
4146        4146    18     31      6                           139818
4147        4147    18     31      9                            21865
4148        4148    18     31      8                           171571
4149        4149    18     32      2                            53403
4150        4150    18     32      1                           567382
4151        4151    18     32      3                             6475
4152        4152    18     32      7                           378373
4153        4153    18     32      4                           243688
4154        4154    18     32      5                           312621
4155        4155    18     32      6                            71008
4156        4156    18     32      9                            11616
4157        4157    18     32      8                            43345

      total_man_by_state_and_level  total_woman_by_state_and_level  \
0                             3157                               0
1                           111212                            7189
2                             3921                            1171
3                           124638                          132994
4                           135145                            5509
5                           226954                          112911
6                            43896                           13380
7                             9284                            5708
8                            59987                            4590
9                             2808                             199
10                          217573                           76612
11                           14338                            5747
12                          418740                          329315
13                          409432                           14506
14                          638491                          426726
15                           75762                           32161
16                           16961                           13442
17                          157981                           13638
18                            4175                             426
19                           87000                           20013
20                            8555                            2379
21                           81908                           81306
22                           97916                            3799
23                           36496                           17435
24                           19059                            5248
25                            3522                            3288
26                           32888                            5288
27                           20021                            7860
28                          252119                           17968
29                            4528                             808
...                            ...                             ...
4128                         35750                            8921
4129                          4747                            2899
4130                         56950                            2394
4131                         49169                            4840
4132                       2980209                          180592
4133                         70471                           14368
4134                        855580                         1160071
4135                       1195322                           29095
4136                        718039                          328190
4137                        216266                           94600
4138                         40953                           27725
4139                        641588                           43155
4140                          7700                            1365
4141                        392750                           28770
4142                         15913                            2424
4143                        268455                          354093
4144                        349246                           17454
4145                        382879                          347227
4146                        103883                           35935
4147                         14987                            6878
4148                        160754                           10817
4149                         51668                            1735
4150                        500847                           66535
4151                          5327                            1148
4152                        156747                          221626
4153                        239972                            3716
4154                        203655                          108966
4155                         54484                           16524
4156                          8549                            3067
4157                         38394                            4951

      total_people_by_state_and_year  total_man_by_state_and_year  \
0                            1001646                       718194
1                            1001646                       718194
2                            1001646                       718194
3                            1001646                       718194
4                            1001646                       718194
5                            1001646                       718194
6                            1001646                       718194
7                            1001646                       718194
8                            1001646                       718194
9                            2864432                      1952086
10                           2864432                      1952086
11                           2864432                      1952086
12                           2864432                      1952086
13                           2864432                      1952086
14                           2864432                      1952086
15                           2864432                      1952086
16                           2864432                      1952086
17                           2864432                      1952086
18                            510701                       371519
19                            510701                       371519
20                            510701                       371519
21                            510701                       371519
22                            510701                       371519
23                            510701                       371519
24                            510701                       371519
25                            510701                       371519
26                            510701                       371519
27                            821042                       593926
28                            821042                       593926
29                            821042                       593926
...                              ...                          ...
4128                         1579033                      1055033
4129                         1579033                      1055033
4130                         1579033                      1055033
4131                         8650233                      6767597
4132                         8650233                      6767597
4133                         8650233                      6767597
4134                         8650233                      6767597
4135                         8650233                      6767597
4136                         8650233                      6767597
4137                         8650233                      6767597
4138                         8650233                      6767597
4139                         8650233                      6767597
4140                         2501530                      1696567
4141                         2501530                      1696567
4142                         2501530                      1696567
4143                         2501530                      1696567
4144                         2501530                      1696567
4145                         2501530                      1696567
4146                         2501530                      1696567
4147                         2501530                      1696567
4148                         2501530                      1696567
4149                         1687911                      1259643
4150                         1687911                      1259643
4151                         1687911                      1259643
4152                         1687911                      1259643
4153                         1687911                      1259643
4154                         1687911                      1259643
4155                         1687911                      1259643
4156                         1687911                      1259643
4157                         1687911                      1259643

      total_woman_by_state_and_year  man_percentage_by_state_and_level  \
0                            283452                            100.000
1                            283452                             93.928
2                            283452                             77.003
3                            283452                             48.378
4                            283452                             96.083
5                            283452                             66.778
6                            283452                             76.639
7                            283452                             61.926
8                            283452                             92.892
9                            912346                             93.382
10                           912346                             73.958
11                           912346                             71.387
12                           912346                             55.977
13                           912346                             96.578
14                           912346                             59.940
15                           912346                             70.200
16                           912346                             55.787
17                           912346                             92.053
18                           139182                             90.741
19                           139182                             81.299
20                           139182                             78.242
21                           139182                             50.184
22                           139182                             96.265
23                           139182                             67.672
24                           139182                             78.410
25                           139182                             51.718
26                           139182                             86.148
27                           227116                             71.809
28                           227116                             93.347
29                           227116                             84.858
...                             ...                                ...
4128                         524000                             80.030
4129                         524000                             62.085
4130                         524000                             95.966
4131                        1882636                             91.039
4132                        1882636                             94.287
4133                        1882636                             83.064
4134                        1882636                             42.447
4135                        1882636                             97.624
4136                        1882636                             68.631
4137                        1882636                             69.569
4138                        1882636                             59.630
4139                        1882636                             93.698
4140                         804963                             84.942
4141                         804963                             93.175
4142                         804963                             86.781
4143                         804963                             43.122
4144                         804963                             95.240
4145                         804963                             52.442
4146                         804963                             74.299
4147                         804963                             68.543
4148                         804963                             93.695
4149                         428268                             96.751
4150                         428268                             88.273
4151                         428268                             82.270
4152                         428268                             41.427
4153                         428268                             98.475
4154                         428268                             65.144
4155                         428268                             76.729
4156                         428268                             73.597
4157                         428268                             88.578

      woman_percentage_by_state_and_level  rate_level  \
0                                   0.000           2
1                                   6.072           1
2                                  22.997           2
3                                  51.622           1
4                                   3.917           1
5                                  33.222           2
6                                  23.361           2
7                                  38.074           0
8                                   7.108           1
9                                   6.618           2
10                                 26.042           1
11                                 28.613           2
12                                 44.023           1
13                                  3.422           1
14                                 40.060           2
15                                 29.800           1
16                                 44.213           0
17                                  7.947           2
18                                  9.259           2
19                                 18.701           1
20                                 21.758           2
21                                 49.816           2
22                                  3.735           2
23                                 32.328           2
24                                 21.590           1
25                                 48.282           0
26                                 13.852           1
27                                 28.191           2
28                                  6.653           1
29                                 15.142           1
...                                   ...         ...
4128                               19.970           2
4129                               37.915           0
4130                                4.034           2
4131                                8.961           2
4132                                5.713           1
4133                               16.936           1
4134                               57.553           1
4135                                2.376           1
4136                               31.369           2
4137                               30.431           2
4138                               40.370           0
4139                                6.302           1
4140                               15.058           1
4141                                6.825           2
4142                               13.219           2
4143                               56.878           2
4144                                4.760           1
4145                               47.558           2
4146                               25.701           2
4147                               31.457           0
4148                                6.305           1
4149                                3.249           1
4150                               11.727           2

In [3]:
df1 = pd.read_csv("Poblacion_Subordinada_Nivel_Ingresos.csv", sep = ',', header=[0], encoding="latin1") 
print(df1)

         Periodo Entidad_Federativa    Sexo     Grupo_edad  \
0       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
1       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
2       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
3       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
4       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
5       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
6       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
7       20050301     Aguascalientes  Hombre   15 A 24 A¥OS
8       20050301     Aguascalientes  Hombre   25 A 44 A¥OS
9       20050301     Aguascalientes  Hombre   25 A 44 A¥OS
10      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
11      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
12      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
13      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
14      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
15      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
16      20050301     Aguascalientes  Hombre   25 A 44 A¥OS
17      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
18      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
19      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
20      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
21      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
22      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
23      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
24      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
25      20050301     Aguascalientes  Hombre   45 A 64 A¥OS
26      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS
27      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS
28      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS
29      20050301     Aguascalientes  Hombre  65 A¥OS Y MAS
...          ...                ...     ...            ...
225696  20190601          Zacatecas  Hombre  65 A¥OS Y MAS
225697  20190601          Zacatecas  Hombre  65 A¥OS Y MAS
225698  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225699  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225700  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225701  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225702  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225703  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225704  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225705  20190601          Zacatecas   Mujer   15 A 24 A¥OS
225706  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225707  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225708  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225709  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225710  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225711  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225712  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225713  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225714  20190601          Zacatecas   Mujer   25 A 44 A¥OS
225715  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225716  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225717  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225718  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225719  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225720  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225721  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225722  20190601          Zacatecas   Mujer   45 A 64 A¥OS
225723  20190601          Zacatecas   Mujer  65 A¥OS Y MAS
225724  20190601          Zacatecas   Mujer  65 A¥OS Y MAS
225725  20190601          Zacatecas   Mujer  65 A¥OS Y MAS

                 Nivel_ingreso  Numero_personas
0              Menos de 1 s.m.             4284
1             1 salario m¡nimo              179
2        M s de 2 hasta 3 s.m.            10503
3        M s de 3 hasta 5 s.m.            16803
4       M s de 5 hasta 10 s.m.             1955
5               M s de 10 s.m.             8368
6           No recibe ingresos             1518
7              No especificado              348
8              Menos de 1 s.m.             9679
9             1 salario m¡nimo              450
10       M s de 1 hasta 2 s.m.              763
11       M s de 2 hasta 3 s.m.            17933
12       M s de 3 hasta 5 s.m.            30257
13      M s de 5 hasta 10 s.m.             5400
14              M s de 10 s.m.            12590
15          No recibe ingresos             9297
16             No especificado             1159
17             Menos de 1 s.m.             8331
18            1 salario m¡nimo              253
19       M s de 1 hasta 2 s.m.               67
20       M s de 2 hasta 3 s.m.             7121
21       M s de 3 hasta 5 s.m.             8715
22      M s de 5 hasta 10 s.m.             2541
23              M s de 10 s.m.             6816
24          No recibe ingresos             3788
25             No especificado              522
26             Menos de 1 s.m.             2580
27       M s de 2 hasta 3 s.m.              399
28       M s de 3 hasta 5 s.m.              632
29      M s de 5 hasta 10 s.m.              298
...                        ...              ...
225696      No recibe ingresos               34
225697         No especificado               36
225698         Menos de 1 s.m.             1708
225699        1 salario m¡nimo              478
225700   M s de 2 hasta 3 s.m.              141
225701   M s de 3 hasta 5 s.m.            10309
225702  M s de 5 hasta 10 s.m.              633
225703          M s de 10 s.m.            13411
225704      No recibe ingresos               50
225705         No especificado               84
225706         Menos de 1 s.m.             6426
225707        1 salario m¡nimo              405
225708   M s de 1 hasta 2 s.m.              495
225709   M s de 2 hasta 3 s.m.              473
225710   M s de 3 hasta 5 s.m.            16134
225711  M s de 5 hasta 10 s.m.             1499
225712          M s de 10 s.m.            29510
225713      No recibe ingresos              112
225714         No especificado              314
225715         Menos de 1 s.m.             4313
225716        1 salario m¡nimo               96
225717   M s de 2 hasta 3 s.m.              194
225718   M s de 3 hasta 5 s.m.             8390
225719  M s de 5 hasta 10 s.m.              294
225720          M s de 10 s.m.            22803
225721      No recibe ingresos              136
225722         No especificado              561
225723         Menos de 1 s.m.             1521
225724   M s de 3 hasta 5 s.m.             1281
225725          M s de 10 s.m.             6080

[225726 rows x 6 columns]

In [4]:
df1.columns

Index(['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso',
       'Numero_personas'],
      dtype='object')

In [5]:
from sklearn import preprocessing
label_encoded = preprocessing.LabelEncoder()

def encode_column(column):
    label_to_number = column
    label_to_number = label_encoded.fit_transform(label_to_number)
    return label_to_number

In [6]:
def add_column_to_df(columnName, df, valueColumn):
    df[columnName] = valueColumn
    return df1

In [7]:
age_to_number = encode_column(df1.Grupo_edad)
age_to_number

array([0, 0, 0, ..., 3, 3, 3])

In [8]:
df1 = add_column_to_df('Age_number', df1, age_to_number)
df1

,Periodo,Entidad_Federativa,Sexo,Grupo_edad,Nivel_ingreso,Numero_personas,Age_number
0,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,Menos de 1 s.m.,4284,0
1,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,1 salario m¡nimo,179,0
2,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,10503,0
3,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,16803,0
4,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,1955,0
5,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 10 s.m.,8368,0
6,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No recibe ingresos,1518,0
7,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No especificado,348,0
8,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,Menos de 1 s.m.,9679,1
9,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,1 salario m¡nimo,450,1
10,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,763,1
11,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,17933,1
12,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,30257,1
13,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,5400,1
14,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 10 s.m.,12590,1
15,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No recibe ingresos,9297,1
16,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No especificado,1159,1
17,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,Menos de 1 s.m.,8331,2
18,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,1 salario m¡nimo,253,2
19,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 1 hasta 2 s.m.,67,2
20,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,7121,2
21,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8715,2
22,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,2541,2
23,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 10 s.m.,6816,2
24,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No recibe ingresos,3788,2
25,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No especificado,522,2
26,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,Menos de 1 s.m.,2580,3
27,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 2 hasta 3 s.m.,399,3
28,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,632,3
29,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 5 hasta 10 s.m.,298,3
...,...,...,...,...,...,...,...
225696,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No recibe ingresos,34,3
225697,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No especificado,36,3
225698,20190601,Zacatecas,Mujer,15 A 24 A¥OS,Menos de 1 s.m.,1708,0
225699,20190601,Zacatecas,Mujer,15 A 24 A¥OS,1 salario m¡nimo,478,0
225700,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,141,0
225701,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,10309,0
225702,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,633,0
225703,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 10 s.m.,13411,0
225704,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No recibe ingresos,50,0
225705,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No especificado,84,0
225706,20190601,Zacatecas,Mujer,25 A 44 A¥OS,Menos de 1 s.m.,6426,1
225707,20190601,Zacatecas,Mujer,25 A 44 A¥OS,1 salario m¡nimo,405,1
225708,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,495,1
225709,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,473,1
225710,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,16134,1
225711,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,1499,1
225712,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 10 s.m.,29510,1
225713,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No recibe ingresos,112,1
225714,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No especificado,314,1
225715,20190601,Zacatecas,Mujer,45 A 64 A¥OS,Menos de 1 s.m.,4313,2
225716,20190601,Zacatecas,Mujer,45 A 64 A¥OS,1 salario m¡nimo,96,2
225717,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,194,2
225718,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8390,2
225719,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,294,2
225720,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 10 s.m.,22803,2
225721,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No recibe ingresos,136,2
225722,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No especificado,561,2
225723,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,Menos de 1 s.m.,1521,3
225724,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,1281,3
225725,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 10 s.m.,6080,3

In [9]:
income_to_number = encode_column(df1.Nivel_ingreso)
income_to_number

array([1, 0, 4, ..., 1, 5, 3])

In [10]:
df1 = add_column_to_df('Income_number', df1, income_to_number)
df1

,Periodo,Entidad_Federativa,Sexo,Grupo_edad,Nivel_ingreso,Numero_personas,Age_number,Income_number
0,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,Menos de 1 s.m.,4284,0,1
1,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,1 salario m¡nimo,179,0,0
2,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,10503,0,4
3,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,16803,0,5
4,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,1955,0,6
5,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 10 s.m.,8368,0,3
6,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No recibe ingresos,1518,0,8
7,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No especificado,348,0,7
8,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,Menos de 1 s.m.,9679,1,1
9,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,1 salario m¡nimo,450,1,0
10,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,763,1,2
11,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,17933,1,4
12,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,30257,1,5
13,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,5400,1,6
14,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 10 s.m.,12590,1,3
15,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No recibe ingresos,9297,1,8
16,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No especificado,1159,1,7
17,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,Menos de 1 s.m.,8331,2,1
18,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,1 salario m¡nimo,253,2,0
19,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 1 hasta 2 s.m.,67,2,2
20,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,7121,2,4
21,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8715,2,5
22,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,2541,2,6
23,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 10 s.m.,6816,2,3
24,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No recibe ingresos,3788,2,8
25,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No especificado,522,2,7
26,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,Menos de 1 s.m.,2580,3,1
27,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 2 hasta 3 s.m.,399,3,4
28,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,632,3,5
29,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 5 hasta 10 s.m.,298,3,6
...,...,...,...,...,...,...,...,...
225696,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No recibe ingresos,34,3,8
225697,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No especificado,36,3,7
225698,20190601,Zacatecas,Mujer,15 A 24 A¥OS,Menos de 1 s.m.,1708,0,1
225699,20190601,Zacatecas,Mujer,15 A 24 A¥OS,1 salario m¡nimo,478,0,0
225700,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,141,0,4
225701,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,10309,0,5
225702,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,633,0,6
225703,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 10 s.m.,13411,0,3
225704,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No recibe ingresos,50,0,8
225705,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No especificado,84,0,7
225706,20190601,Zacatecas,Mujer,25 A 44 A¥OS,Menos de 1 s.m.,6426,1,1
225707,20190601,Zacatecas,Mujer,25 A 44 A¥OS,1 salario m¡nimo,405,1,0
225708,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,495,1,2
225709,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,473,1,4
225710,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,16134,1,5
225711,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,1499,1,6
225712,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 10 s.m.,29510,1,3
225713,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No recibe ingresos,112,1,8
225714,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No especificado,314,1,7
225715,20190601,Zacatecas,Mujer,45 A 64 A¥OS,Menos de 1 s.m.,4313,2,1
225716,20190601,Zacatecas,Mujer,45 A 64 A¥OS,1 salario m¡nimo,96,2,0
225717,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,194,2,4
225718,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8390,2,5
225719,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,294,2,6
225720,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 10 s.m.,22803,2,3
225721,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No recibe ingresos,136,2,8
225722,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No especificado,561,2,7
225723,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,Menos de 1 s.m.,1521,3,1
225724,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,1281,3,5
225725,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 10 s.m.,6080,3,3

In [11]:
state_to_number = encode_column(df1.Entidad_Federativa)
state_to_number

df1 = add_column_to_df('State_number', df1, state_to_number)
df1

,Periodo,Entidad_Federativa,Sexo,Grupo_edad,Nivel_ingreso,Numero_personas,Age_number,Income_number,State_number
0,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,Menos de 1 s.m.,4284,0,1,0
1,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,1 salario m¡nimo,179,0,0,0
2,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,10503,0,4,0
3,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,16803,0,5,0
4,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,1955,0,6,0
5,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 10 s.m.,8368,0,3,0
6,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No recibe ingresos,1518,0,8,0
7,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No especificado,348,0,7,0
8,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,Menos de 1 s.m.,9679,1,1,0
9,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,1 salario m¡nimo,450,1,0,0
10,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,763,1,2,0
11,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,17933,1,4,0
12,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,30257,1,5,0
13,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,5400,1,6,0
14,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 10 s.m.,12590,1,3,0
15,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No recibe ingresos,9297,1,8,0
16,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No especificado,1159,1,7,0
17,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,Menos de 1 s.m.,8331,2,1,0
18,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,1 salario m¡nimo,253,2,0,0
19,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 1 hasta 2 s.m.,67,2,2,0
20,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,7121,2,4,0
21,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8715,2,5,0
22,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,2541,2,6,0
23,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 10 s.m.,6816,2,3,0
24,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No recibe ingresos,3788,2,8,0
25,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No especificado,522,2,7,0
26,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,Menos de 1 s.m.,2580,3,1,0
27,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 2 hasta 3 s.m.,399,3,4,0
28,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,632,3,5,0
29,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 5 hasta 10 s.m.,298,3,6,0
...,...,...,...,...,...,...,...,...,...
225696,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No recibe ingresos,34,3,8,32
225697,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No especificado,36,3,7,32
225698,20190601,Zacatecas,Mujer,15 A 24 A¥OS,Menos de 1 s.m.,1708,0,1,32
225699,20190601,Zacatecas,Mujer,15 A 24 A¥OS,1 salario m¡nimo,478,0,0,32
225700,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,141,0,4,32
225701,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,10309,0,5,32
225702,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,633,0,6,32
225703,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 10 s.m.,13411,0,3,32
225704,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No recibe ingresos,50,0,8,32
225705,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No especificado,84,0,7,32
225706,20190601,Zacatecas,Mujer,25 A 44 A¥OS,Menos de 1 s.m.,6426,1,1,32
225707,20190601,Zacatecas,Mujer,25 A 44 A¥OS,1 salario m¡nimo,405,1,0,32
225708,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,495,1,2,32
225709,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,473,1,4,32
225710,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,16134,1,5,32
225711,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,1499,1,6,32
225712,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 10 s.m.,29510,1,3,32
225713,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No recibe ingresos,112,1,8,32
225714,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No especificado,314,1,7,32
225715,20190601,Zacatecas,Mujer,45 A 64 A¥OS,Menos de 1 s.m.,4313,2,1,32
225716,20190601,Zacatecas,Mujer,45 A 64 A¥OS,1 salario m¡nimo,96,2,0,32
225717,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,194,2,4,32
225718,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8390,2,5,32
225719,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,294,2,6,32
225720,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 10 s.m.,22803,2,3,32
225721,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No recibe ingresos,136,2,8,32
225722,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No especificado,561,2,7,32
225723,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,Menos de 1 s.m.,1521,3,1,32
225724,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,1281,3,5,32
225725,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 10 s.m.,6080,3,3,32

In [12]:
sex_to_number = encode_column(df1.Sexo)
sex_to_number

df1 = add_column_to_df('Sex_number', df1, sex_to_number)
df1

,Periodo,Entidad_Federativa,Sexo,Grupo_edad,Nivel_ingreso,Numero_personas,Age_number,Income_number,State_number,Sex_number
0,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,Menos de 1 s.m.,4284,0,1,0,0
1,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,1 salario m¡nimo,179,0,0,0,0
2,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,10503,0,4,0,0
3,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,16803,0,5,0,0
4,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,1955,0,6,0,0
5,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,M s de 10 s.m.,8368,0,3,0,0
6,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No recibe ingresos,1518,0,8,0,0
7,20050301,Aguascalientes,Hombre,15 A 24 A¥OS,No especificado,348,0,7,0,0
8,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,Menos de 1 s.m.,9679,1,1,0,0
9,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,1 salario m¡nimo,450,1,0,0,0
10,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,763,1,2,0,0
11,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,17933,1,4,0,0
12,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,30257,1,5,0,0
13,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,5400,1,6,0,0
14,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,M s de 10 s.m.,12590,1,3,0,0
15,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No recibe ingresos,9297,1,8,0,0
16,20050301,Aguascalientes,Hombre,25 A 44 A¥OS,No especificado,1159,1,7,0,0
17,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,Menos de 1 s.m.,8331,2,1,0,0
18,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,1 salario m¡nimo,253,2,0,0,0
19,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 1 hasta 2 s.m.,67,2,2,0,0
20,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,7121,2,4,0,0
21,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8715,2,5,0,0
22,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,2541,2,6,0,0
23,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,M s de 10 s.m.,6816,2,3,0,0
24,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No recibe ingresos,3788,2,8,0,0
25,20050301,Aguascalientes,Hombre,45 A 64 A¥OS,No especificado,522,2,7,0,0
26,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,Menos de 1 s.m.,2580,3,1,0,0
27,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 2 hasta 3 s.m.,399,3,4,0,0
28,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,632,3,5,0,0
29,20050301,Aguascalientes,Hombre,65 A¥OS Y MAS,M s de 5 hasta 10 s.m.,298,3,6,0,0
...,...,...,...,...,...,...,...,...,...,...
225696,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No recibe ingresos,34,3,8,32,0
225697,20190601,Zacatecas,Hombre,65 A¥OS Y MAS,No especificado,36,3,7,32,0
225698,20190601,Zacatecas,Mujer,15 A 24 A¥OS,Menos de 1 s.m.,1708,0,1,32,1
225699,20190601,Zacatecas,Mujer,15 A 24 A¥OS,1 salario m¡nimo,478,0,0,32,1
225700,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 2 hasta 3 s.m.,141,0,4,32,1
225701,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 3 hasta 5 s.m.,10309,0,5,32,1
225702,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 5 hasta 10 s.m.,633,0,6,32,1
225703,20190601,Zacatecas,Mujer,15 A 24 A¥OS,M s de 10 s.m.,13411,0,3,32,1
225704,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No recibe ingresos,50,0,8,32,1
225705,20190601,Zacatecas,Mujer,15 A 24 A¥OS,No especificado,84,0,7,32,1
225706,20190601,Zacatecas,Mujer,25 A 44 A¥OS,Menos de 1 s.m.,6426,1,1,32,1
225707,20190601,Zacatecas,Mujer,25 A 44 A¥OS,1 salario m¡nimo,405,1,0,32,1
225708,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 1 hasta 2 s.m.,495,1,2,32,1
225709,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 2 hasta 3 s.m.,473,1,4,32,1
225710,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 3 hasta 5 s.m.,16134,1,5,32,1
225711,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 5 hasta 10 s.m.,1499,1,6,32,1
225712,20190601,Zacatecas,Mujer,25 A 44 A¥OS,M s de 10 s.m.,29510,1,3,32,1
225713,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No recibe ingresos,112,1,8,32,1
225714,20190601,Zacatecas,Mujer,25 A 44 A¥OS,No especificado,314,1,7,32,1
225715,20190601,Zacatecas,Mujer,45 A 64 A¥OS,Menos de 1 s.m.,4313,2,1,32,1
225716,20190601,Zacatecas,Mujer,45 A 64 A¥OS,1 salario m¡nimo,96,2,0,32,1
225717,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 2 hasta 3 s.m.,194,2,4,32,1
225718,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 3 hasta 5 s.m.,8390,2,5,32,1
225719,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 5 hasta 10 s.m.,294,2,6,32,1
225720,20190601,Zacatecas,Mujer,45 A 64 A¥OS,M s de 10 s.m.,22803,2,3,32,1
225721,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No recibe ingresos,136,2,8,32,1
225722,20190601,Zacatecas,Mujer,45 A 64 A¥OS,No especificado,561,2,7,32,1
225723,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,Menos de 1 s.m.,1521,3,1,32,1
225724,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 3 hasta 5 s.m.,1281,3,5,32,1
225725,20190601,Zacatecas,Mujer,65 A¥OS Y MAS,M s de 10 s.m.,6080,3,3,32,1

In [17]:
len_df1_cols = len(df1.columns)
print (list(df1.columns), len_df1_cols)

print (df1.columns)

['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso', 'Numero_personas', 'Age_number', 'Income_number', 'State_number', 'Sex_number'] 10
Index(['Periodo', 'Entidad_Federativa', 'Sexo', 'Grupo_edad', 'Nivel_ingreso',
       'Numero_personas', 'Age_number', 'Income_number', 'State_number',
       'Sex_number'],
      dtype='object')

In [19]:
df1['Age_number'].unique()

array([0, 1, 2, 3, 4])

In [23]:
df1['Grupo_edad'].unique()

array(['15 A 24 A¥OS', '25 A 44 A¥OS', '45 A 64 A¥OS', '65 A¥OS Y MAS',
       'NO ESPECIFICADO'], dtype=object)

In [20]:
df1['Income_number'].unique()

array([1, 0, 4, 5, 6, 3, 8, 7, 2])

In [24]:
df1['Nivel_ingreso'].unique()

array(['Menos de 1 s.m.', '1 salario m¡nimo', 'M\xa0s de 2 hasta 3 s.m.',
       'M\xa0s de 3 hasta 5 s.m.', 'M\xa0s de 5 hasta 10 s.m.',
       'M\xa0s de 10 s.m.', 'No recibe ingresos', 'No especificado',
       'M\xa0s de 1 hasta 2 s.m.'], dtype=object)

In [21]:
df1['State_number'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 17])

In [25]:
df1['Entidad_Federativa'].unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de M\x82xico',
       'Coahuila', 'Colima', 'Durango', 'Estado de M\x82xico',
       'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Michoac\xa0n',
       'Morelos', 'Nayarit', 'Nuevo Le¢n', 'Oaxaca', 'Puebla',
       'Queretaro', 'Quintana Roo', 'San Luis Potos¡', 'Sinaloa',
       'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz',
       'Yucat\xa0n', 'Zacatecas', 'Nacional'], dtype=object)

In [22]:
df1['Sex_number'].unique()

array([0, 1])

In [26]:
df1['Sexo'].unique()

array(['Hombre', 'Mujer'], dtype=object)

In [5]:
# print the dataframe
print (df)

# plot the Stock Index Price(dependent ) vs Interest Rate (independent)
plt.scatter(df['Interest_Rate'], df['Stock_Index_Price'], color='red')
plt.title('Stock Index Price Vs Interest Rate', fontsize=14)
plt.xlabel('Interest Rate', fontsize=14)
plt.ylabel('Stock Index Price', fontsize=14)
plt.grid(True)
plt.show()

# plot the Stock Index Price (dependent) vs Unemployment Rate (independent)
plt.scatter(df['Unemployment_Rate'], df['Stock_Index_Price'], color='green')
plt.title('Stock Index Price Vs Unemployment Rate', fontsize=14)
plt.xlabel('Unemployment Rate', fontsize=14)
plt.ylabel('Stock Index Price', fontsize=14)
plt.grid(True)
plt.show()

      Unnamed: 0  year  state  level  total_people_by_state_and_level  \
0              0     5      1      2                             3157
1              1     5      1      1                           118401
2              2     5      1      3                             5092
3              3     5      1      7                           257632
4              4     5      1      4                           140654
5              5     5      1      5                           339865
6              6     5      1      6                            57276
7              7     5      1      9                            14992
8              8     5      1      8                            64577
9              9     5      2      2                             3007
10            10     5      2      1                           294185
11            11     5      2      3                            20085
12            12     5      2      7                           748055
13            13     5      2      4                           423938
14            14     5      2      5                          1065217
15            15     5      2      6                           107923
16            16     5      2      9                            30403
17            17     5      2      8                           171619
18            18     5      3      2                             4601
19            19     5      3      1                           107013
20            20     5      3      3                            10934
21            21     5      3      7                           163214
22            22     5      3      4                           101715
23            23     5      3      5                            53931
24            24     5      3      6                            24307
25            25     5      3      9                             6810
26            26     5      3      8                            38176
27            27     5      4      2                            27881
28            28     5      4      1                           270087
29            29     5      4      3                             5336
...          ...   ...    ...    ...                              ...
4128        4128    18     29      6                            44671
4129        4129    18     29      9                             7646
4130        4130    18     29      8                            59344
4131        4131    18     30      2                            54009
4132        4132    18     30      1                          3160801
4133        4133    18     30      3                            84839
4134        4134    18     30      7                          2015651
4135        4135    18     30      4                          1224417
4136        4136    18     30      5                          1046229
4137        4137    18     30      6                           310866
4138        4138    18     30      9                            68678
4139        4139    18     30      8                           684743
4140        4140    18     31      2                             9065
4141        4141    18     31      1                           421520
4142        4142    18     31      3                            18337
4143        4143    18     31      7                           622548
4144        4144    18     31      4                           366700
4145        4145    18     31      5                           730106
4146        4146    18     31      6                           139818
4147        4147    18     31      9                            21865
4148        4148    18     31      8                           171571
4149        4149    18     32      2                            53403
4150        4150    18     32      1                           567382
4151        4151    18     32      3                             6475
4152        4152    18     32      7                           378373
4153        4153    18     32      4                           243688
4154        4154    18     32      5                           312621
4155        4155    18     32      6                            71008
4156        4156    18     32      9                            11616
4157        4157    18     32      8                            43345

      total_man_by_state_and_level  total_woman_by_state_and_level  \
0                             3157                               0
1                           111212                            7189
2                             3921                            1171
3                           124638                          132994
4                           135145                            5509
5                           226954                          112911
6                            43896                           13380
7                             9284                            5708
8                            59987                            4590
9                             2808                             199
10                          217573                           76612
11                           14338                            5747
12                          418740                          329315
13                          409432                           14506
14                          638491                          426726
15                           75762                           32161
16                           16961                           13442
17                          157981                           13638
18                            4175                             426
19                           87000                           20013
20                            8555                            2379
21                           81908                           81306
22                           97916                            3799
23                           36496                           17435
24                           19059                            5248
25                            3522                            3288
26                           32888                            5288
27                           20021                            7860
28                          252119                           17968
29                            4528                             808
...                            ...                             ...
4128                         35750                            8921
4129                          4747                            2899
4130                         56950                            2394
4131                         49169                            4840
4132                       2980209                          180592
4133                         70471                           14368
4134                        855580                         1160071
4135                       1195322                           29095
4136                        718039                          328190
4137                        216266                           94600
4138                         40953                           27725
4139                        641588                           43155
4140                          7700                            1365
4141                        392750                           28770
4142                         15913                            2424
4143                        268455                          354093
4144                        349246                           17454
4145                        382879                          347227
4146                        103883                           35935
4147                         14987                            6878
4148                        160754                           10817
4149                         51668                            1735
4150                        500847                           66535
4151                          5327                            1148
4152                        156747                          221626
4153                        239972                            3716
4154                        203655                          108966
4155                         54484                           16524
4156                          8549                            3067
4157                         38394                            4951

      total_people_by_state_and_year  total_man_by_state_and_year  \
0                            1001646                       718194
1                            1001646                       718194
2                            1001646                       718194
3                            1001646                       718194
4                            1001646                       718194
5                            1001646                       718194
6                            1001646                       718194
7                            1001646                       718194
8                            1001646                       718194
9                            2864432                      1952086
10                           2864432                      1952086
11                           2864432                      1952086
12                           2864432                      1952086
13                           2864432                      1952086
14                           2864432                      1952086
15                           2864432                      1952086
16                           2864432                      1952086
17                           2864432                      1952086
18                            510701                       371519
19                            510701                       371519
20                            510701                       371519
21                            510701                       371519
22                            510701                       371519
23                            510701                       371519
24                            510701                       371519
25                            510701                       371519
26                            510701                       371519
27                            821042                       593926
28                            821042                       593926
29                            821042                       593926
...                              ...                          ...
4128                         1579033                      1055033
4129                         1579033                      1055033
4130                         1579033                      1055033
4131                         8650233                      6767597
4132                         8650233                      6767597
4133                         8650233                      6767597
4134                         8650233                      6767597
4135                         8650233                      6767597
4136                         8650233                      6767597
4137                         8650233                      6767597
4138                         8650233                      6767597
4139                         8650233                      6767597
4140                         2501530                      1696567
4141                         2501530                      1696567
4142                         2501530                      1696567
4143                         2501530                      1696567
4144                         2501530                      1696567
4145                         2501530                      1696567
4146                         2501530                      1696567
4147                         2501530                      1696567
4148                         2501530                      1696567
4149                         1687911                      1259643
4150                         1687911                      1259643
4151                         1687911                      1259643
4152                         1687911                      1259643
4153                         1687911                      1259643
4154                         1687911                      1259643
4155                         1687911                      1259643
4156                         1687911                      1259643
4157                         1687911                      1259643

      total_woman_by_state_and_year  man_percentage_by_state_and_level  \
0                            283452                            100.000
1                            283452                             93.928
2                            283452                             77.003
3                            283452                             48.378
4                            283452                             96.083
5                            283452                             66.778
6                            283452                             76.639
7                            283452                             61.926
8                            283452                             92.892
9                            912346                             93.382
10                           912346                             73.958
11                           912346                             71.387
12                           912346                             55.977
13                           912346                             96.578
14                           912346                             59.940
15                           912346                             70.200
16                           912346                             55.787
17                           912346                             92.053
18                           139182                             90.741
19                           139182                             81.299
20                           139182                             78.242
21                           139182                             50.184
22                           139182                             96.265
23                           139182                             67.672
24                           139182                             78.410
25                           139182                             51.718
26                           139182                             86.148
27                           227116                             71.809
28                           227116                             93.347
29                           227116                             84.858
...                             ...                                ...
4128                         524000                             80.030
4129                         524000                             62.085
4130                         524000                             95.966
4131                        1882636                             91.039
4132                        1882636                             94.287
4133                        1882636                             83.064
4134                        1882636                             42.447
4135                        1882636                             97.624
4136                        1882636                             68.631
4137                        1882636                             69.569
4138                        1882636                             59.630
4139                        1882636                             93.698
4140                         804963                             84.942
4141                         804963                             93.175
4142                         804963                             86.781
4143                         804963                             43.122
4144                         804963                             95.240
4145                         804963                             52.442
4146                         804963                             74.299
4147                         804963                             68.543
4148                         804963                             93.695
4149                         428268                             96.751
4150                         428268                             88.273
4151                         428268                             82.270
4152                         428268                             41.427
4153                         428268                             98.475
4154                         428268                             65.144
4155                         428268                             76.729
4156                         428268                             73.597
4157                         428268                             88.578

      woman_percentage_by_state_and_level  rate_level  \
0                                   0.000           2
1                                   6.072           1
2                                  22.997           2
3                                  51.622           1
4                                   3.917           1
5                                  33.222           2
6                                  23.361           2
7                                  38.074           0
8                                   7.108           1
9                                   6.618           2
10                                 26.042           1
11                                 28.613           2
12                                 44.023           1
13                                  3.422           1
14                                 40.060           2
15                                 29.800           1
16                                 44.213           0
17                                  7.947           2
18                                  9.259           2
19                                 18.701           1
20                                 21.758           2
21                                 49.816           2
22                                  3.735           2
23                                 32.328           2
24                                 21.590           1
25                                 48.282           0
26                                 13.852           1
27                                 28.191           2
28                                  6.653           1
29                                 15.142           1
...                                   ...         ...
4128                               19.970           2
4129                               37.915           0
4130                                4.034           2
4131                                8.961           2
4132                                5.713           1
4133                               16.936           1
4134                               57.553           1
4135                                2.376           1
4136                               31.369           2
4137                               30.431           2
4138                               40.370           0
4139                                6.302           1
4140                               15.058           1
4141                                6.825           2
4142                               13.219           2
4143                               56.878           2
4144                                4.760           1
4145                               47.558           2
4146                               25.701           2
4147                               31.457           0
4148                                6.305           1
4149                                3.249           1
4150                               11.727           2

KeyError: 'Interest_Rate'

In [15]:
# Split independent vars(X) and dependent var(Y)
# here we have 2 variables for multiple regression. 
#If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.
#Alternatively, you may add additional variables within the brackets
X = df1[['Numero_personas','Age_number','State_number','Sex_number']] 
Y = df1['Income_number']
 
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)


# prediction with sklearn
Num_persons = 50000
Age_number = 4
State_number = 20
Sex_number = 0
print ('Predicted Income group : \n', regr.predict([[Num_persons, Age_number, State_number, Sex_number]]))

Intercept:
 4.482457479513848
Coefficients:
 [-7.87335893e-06 -1.08152459e-01 -2.77350755e-03  6.77843532e-02]
Predicted Income group :
 [3.60070954]

In [16]:
# with statsmodels
X = sm.add_constant(X) # adding a constant
 
model = sm.OLS(Y, X).fit()
predictions = model.predict(X) 
 
print_model = model.summary()
print(print_model)

/home/ealarap/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

                            OLS Regression Results
==============================================================================
Dep. Variable:          Income_number   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     719.0
Date:                Wed, 06 Nov 2019   Prob (F-statistic):               0.00
Time:                        09:28:59   Log-Likelihood:            -5.2099e+05
No. Observations:              225726   AIC:                         1.042e+06
Df Residuals:                  225721   BIC:                         1.042e+06
Df Model:                           4
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               4.4825      0.016    275.722      0.000       4.451       4.514
Numero_personas -7.873e-06   1.64e-07    -48.046      0.000   -8.19e-06   -7.55e-06
Age_number         -0.1082      0.005    -22.806      0.000      -0.117      -0.099
State_number       -0.0028      0.001     -3.708      0.000      -0.004      -0.001
Sex_number          0.0678      0.010      6.476      0.000       0.047       0.088
==============================================================================
Omnibus:                    80432.472   Durbin-Watson:                   1.607
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11263.388
Skew:                          -0.101   Prob(JB):                         0.00
Kurtosis:                       1.924   Cond. No.                     1.17e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [27]:
 tkinter GUI
root= tk.Tk() 
 
canvas1 = tk.Canvas(root, width = 1200, height = 450)
canvas1.pack()

# with sklearn
Intercept_result = ('Intercept: ', regr.intercept_)
label_Intercept = tk.Label(root, text=Intercept_result, justify = 'center')
canvas1.create_window(260, 220, window=label_Intercept)

# with sklearn
Coefficients_result  = ('Coefficients: ', regr.coef_)
label_Coefficients = tk.Label(root, text=Coefficients_result, justify = 'center')
canvas1.create_window(260, 240, window=label_Coefficients)

# with statsmodels
print_model = model.summary()
label_model = tk.Label(root, text=print_model, justify = 'center', relief = 'solid', bg='LightSkyBlue1')
canvas1.create_window(800, 220, window=label_model)


# New_Interest_Rate label and input box
label1 = tk.Label(root, text='Type Interest Rate: ')
canvas1.create_window(100, 100, window=label1)

entry1 = tk.Entry (root) # create 1st entry box
canvas1.create_window(270, 100, window=entry1)

# New_Unemployment_Rate label and input box
label2 = tk.Label(root, text=' Type Unemployment Rate: ')
canvas1.create_window(120, 120, window=label2)

entry2 = tk.Entry (root) # create 2nd entry box
canvas1.create_window(270, 120, window=entry2)


def values(): 
    global New_Interest_Rate #our 1st input variable
    New_Interest_Rate = float(entry1.get()) 
    
    global New_Unemployment_Rate #our 2nd input variable
    New_Unemployment_Rate = float(entry2.get()) 
    
    Prediction_result  = ('Predicted Stock Index Price: ', regr.predict([[New_Interest_Rate ,New_Unemployment_Rate]]))
    label_Prediction = tk.Label(root, text= Prediction_result, bg='orange')
    canvas1.create_window(260, 280, window=label_Prediction)
    
button1 = tk.Button (root, text='Predict Stock Index Price',command=values, bg='orange') # button to call the 'values' command above 
canvas1.create_window(270, 150, window=button1)
 

root.mainloop()

SyntaxError: invalid syntax (<ipython-input-27-219c5b673a42>, line 1)